development:
  adapter: postgresql
  encoding: unicode
  database: booksfaker
  host: localhost
  pool: 5
  username: sky
  password: spindoctor

staging:
  adapter: postgresql
  encoding: unicode
  database: booksfaker
  host: localhost
  pool: 5
  username: sky
  password: spindoctor

test:
  adapter: postgresql
  encoding: unicode
  database: bookstest
  host: localhost
  pool: 5
  username: sky
  password: spindoctor
